version: "3"
services:
  app:
    container_name: easy-archetype-cloud-auth-web
    image: registry.cn-hangzhou.aliyuncs.com/easy-archetype/easy-archetype-cloud-auth-web:1.0-SNAPSHOT
    volumes:
      - ./logs:/logs
    ports:
      - "10001:10001"
    restart: on-failure
    network_mode: host
    environment:
      - "JAVA_OPTS=-Xms128m -Xmx256m -Djava.security.egd=file:/dev/./urandom"
      - "NACOS_ADDR=localhost:8848"

