version: "3"
services:
  app:
    hostname: easy-archetype-cloud-gateway
    container_name: easy-archetype-cloud-gateway
    image: registry.cn-hangzhou.aliyuncs.com/easy-archetype/easy-archetype-cloud-gateway:1.0-SNAPSHOT
    volumes:
      - ./logs:/logs
    ports:
      - "10001:10001"
    restart: always
    environment:
      JAVA_OPTS: "-Xms128m -Xmx256m -Djava.security.egd=file:/dev/./urandom"
      SPRING_PROFILES_ACTIVE: dev
  #      RUN_OPTS: "--server.port=9999"

