## 日志配置
logging:
  level:
    com.easy: debug
    org.springframework: warn

spring:
  thymeleaf:
    # thymeleaf  禁用缓存
    cache: false
    # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true