server:
  ## 端口号
  port: 9000
  servlet:
    ## 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI 编码
    uri-encoding: utf-8
    # tomcat的最大线程池,默认为200
    max-threads: 800
    # tomcat 启动初始化的线程数量，默认为
    min-spare-threads: 30

# Spring的配置
spring:
  # 模板引擎配置
  thymeleaf:
    mode: HTML
    # 编码
    encoding: UTF-8
    # 资源信息
  messages:
    # 国际化资源文件
    basename: static/i18n/messages
    # 序列化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    # 指定启用哪个环境的配置文件
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB




