spring:
  cloud:
    gateway:
      routes:
        # 认证中心
        - id: easy-archetype-cloud-auth
          uri: lb://easy-archetype-cloud-auth
          predicates:
            - Path=/uaa/**
        # 脚手架
        - id: easy-archetype-cloud-archetype
          uri: lb://easy-archetype-cloud-archetype
          predicates:
            - Path=/archetype/**
