version: "3"
services:
  easy-archetype-web-all:
    hostname: easy-archetype-web-all
    container_name: easy-archetype-web-all
    image: registry.cn-hangzhou.aliyuncs.com/easy-archetype/easy-archetype-web-all:1.0-SNAPSHOT
    volumes:
      - ./logs:/logs
    ports:
      - "9999:9999"
    restart: always
    environment:
       JAVA_OPTS: "-Xms128m -Xmx256m -Djava.security.egd=file:/dev/./urandom"
       SPRING_PROFILES_ACTIVE: dev
       RUN_OPTS: "--server.port=9999"

