easy:
  archetype:
    framework:
      file:
        file-host: http://localhost:8080
        server:
          oss:
            bucket-name: test
            access-key: 11111
            endpoint: http://localhost:8080
            region: http://localhost:8080
            secret-key: http://localhost:8080