easy:
  archetype:
    framework:
      file:
        file-host: http://localhost:8080
        server:
          oss:
            bucket-name: easy-archetype
            access-key: root
            endpoint: http://localhost:9001/
            region: http://localhost:8080
            secret-key: password
          endpoint: true

spring:
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true

    username: root
    password: rootroot
com:
  easy:
    archetype:
      job:
        enable: true