version: "3"
services:
  app:
    hostname: easy-archetype-cloud-archetype-web
    container_name: easy-archetype-cloud-archetype-web
    image: registry.cn-hangzhou.aliyuncs.com/easy-archetype/easy-archetype-cloud-archetype-web:1.0-SNAPSHOT
    volumes:
      - ./logs:/logs
    ports:
      - "9002:9002"
    restart: always
    environment:
       JAVA_OPTS: "-Xms128m -Xmx256m -Djava.security.egd=file:/dev/./urandom"
       SPRING_PROFILES_ACTIVE: dev
 #      RUN_OPTS: "--server.port=9999"

