# docker-compose参考：https://github.com/nacos-group/nacos-docker/blob/master/example/standalone-mysql-5.7.yaml
version: '3'
services:
  nacos:
    image: nacos/nacos-server:latest                             # 镜像`nacos/nacos-server:latest`
    container_name: nacos_server                                 # 容器名为'nacos_server'
    restart: always                                              # 指定容器退出后的重启策略为始终重启
    volumes:                                                     # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "./logs:/home/nacos/logs"
      - "./init.d/custom.properties:/home/nacos/init.d/custom.properties"
      - "./conf/application.properties:/home/nacos/conf/application.properties"
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      - PREFER_HOST_MODE=hostname                 # 如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      - MODE=standalone                           # 单机模式启动
      - SPRING_DATASOURCE_PLATFORM=mysql          # 数据源平台 仅支持mysql或不保存empty
      - MYSQL_SERVICE_HOST=easy-mysql  # 注：这里不能为`127.0.0.1`或`localhost`方式！！！
      - MYSQL_SERVICE_DB_NAME=easy-archetype-dev      # 所需sql脚本位于 `nacos-mysql/nacos-mysql.sql`
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=luyanan
      - MYSQL_SERVICE_PASSWORD=luyanan
      # JVM调优参数
      - JVM_XMS=64m   #-Xms default :2g
      - JVM_XMX=64m   #-Xmx default :2g
      - JVM_XMN=16m   #-Xmn default :1g
      - JVM_MS=8m     #-XX:MetaspaceSize default :128m
      - JVM_MMS=8m    #-XX:MaxMetaspaceSize default :320m
      - NACOS_DEBUG=n #是否开启远程debug，y/n，默认n
      - TOMCAT_ACCESSLOG_ENABLED=false #是否开始tomcat访问日志的记录，默认false
    ports:                              # 映射端口
      - "8848:8848"
      - "9555:9555"
    network_mode: host
